language: cpp
sudo: false
addons:
  apt:
    packages:
      - bison
      - flex
      - automake1.11
script:
  - aclocal
  - autoconf
  - ./configure --with-mysql --with-mysql-lib=$(mysql_config --variable=pkglibdir)
  - make
