language: cpp
addons:
  apt:
    packages:
      - bison
      - flex
before_install:
  - wget ftp://ftp.gnu.org/gnu/automake/automake-1.4-p6.tar.gz
  - tar zxvf automake-1.4-p6.tar.gz
  - cd automake-1.4-p6
  - ./configure
  - make
  - sudo make install
script:
  - ./configure --with-mysql --with-mysql-lib=$(mysql_config --variable=pkglibdir)
  - make
